runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: build/es5-bundled/bower_components

- url: /images
  static_dir: build/es5-bundled/images

- url: /src
  static_dir: build/es5-bundled/src

- url: /manifest.json
  static_files: build/es5-bundled/manifest.json
  upload: build/es5-bundled/manifest.json

- url: /service-worker.js
  static_files: build/es5-bundled/service-worker.js
  upload: build/es5-bundled/service-worker.js

- url: /.*
  static_files: build/es5-bundled/index.html
  upload: build/es5-bundled/index.html
